name: Autograding Tests

on:
  - push
  - workflow_dispatch

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4.5.0
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Generate Dependency Tree
        run: mvn -q dependency:tree -DoutputFile=target/dependency-tree.txt -Daggregate=true

      - name: Test data-management dependency test with main-application
        id: test
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Test data-management dependency test with main-application
          setup-command: ''
          command: mvn -B test -Dtest=DataManagementTest#testSensorDataCollectionDependency --file pom.xml -DfailIfNoTests=false
          timeout: 1
          max-score: 0

      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        env:
          TEST: "${{steps.test.outputs.result}}"
        with:
          runners: test